/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 car.gltf --transform
Author: DAVID 3D ART (https://sketchfab.com/david3dart)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/ac-praga-r1-891cd6b490234e0f8d89f35a1d3df24e
Title: AC - Praga R1
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/car-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={153.9}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group position={[0.69, 0.18, 1.23]} rotation={[-0.11, -0.02, 0.14]}>
            <group position={[0.1, 0.09, 0.01]} rotation={[0.11, 0, -0.14]}>
              <group position={[-0.77, -0.29, -1.23]}>
                <mesh
                  geometry={
                    nodes.EXT_RIM_LF_SUB1_INT_PLASTIC_SW_BUTTONS_0.geometry
                  }
                  material={materials.INT_PLASTIC_SW_BUTTONS}
                  position={[0.87, 0.11, 1.17]}
                />
                <mesh
                  geometry={nodes.EXT_RIM_LF_SUB0_EXT_METAL_RIM_0.geometry}
                  material={materials.EXT_METAL_RIM}
                  position={[0.77, 0.29, 1.23]}
                />
              </group>
              <mesh
                geometry={nodes.EXT_TIRE_LF_2_EXT_RUBBER_TIRE_0.geometry}
                material={materials.EXT_RUBBER_TIRE}
              />
            </group>
            <group position={[0.1, 0.09, 0.01]} rotation={[0.11, 0, -0.14]}>
              <group position={[-0.77, -0.29, -1.71]}>
                <mesh
                  geometry={nodes.FL_DISKBRAKE_mesh_2_EXT_METAL_DISK_0.geometry}
                  material={materials.EXT_METAL_DISK}
                  position={[0.75, 0.29, 1.71]}
                />
              </group>
            </group>
            <group position={[-0.71, 0.06, -1.23]} rotation={[0.11, 0, -0.14]}>
              <mesh
                geometry={nodes.GEO_hub1_SUB1_GEO_hub1_0.geometry}
                material={materials.GEO_hub1}
                position={[0.75, 0.28, 1.11]}
              />
              <mesh
                geometry={
                  nodes.GEO_hub1_SUB0_EXT_METAL_SHINY_EXHAUST_0.geometry
                }
                material={materials.EXT_METAL_SHINY_EXHAUST}
                position={[0.7, 0.29, 1.22]}
              />
              <mesh
                geometry={nodes.GEO_hub1_SUB2_INT_METAL_BOLTS_0.geometry}
                material={materials.INT_METAL_BOLTS}
                position={[0.72, 0.29, 1.19]}
              />
            </group>
            <group position={[0.05, 0.21, 0.11]} rotation={[-3, -0.15, -3.07]}>
              <mesh
                geometry={
                  nodes.susp_steering_arm_lf_2_EXT_METAL_SHINY_EXHAUST_0
                    .geometry
                }
                material={materials.EXT_METAL_SHINY_EXHAUST}
                position={[0.22, 0, 0]}
              />
            </group>
          </group>
          <group position={[-0.69, 0.18, 1.23]} rotation={[-0.11, 0.02, -0.14]}>
            <group position={[-0.1, 0.09, 0.01]} rotation={[0.11, 0, 0.14]}>
              <group position={[0.77, -0.29, -1.23]}>
                <mesh
                  geometry={
                    nodes.EXT_RIM_LF1_SUB1_INT_PLASTIC_SW_BUTTONS_0.geometry
                  }
                  material={materials.INT_PLASTIC_SW_BUTTONS}
                  position={[-0.87, 0.11, 1.17]}
                />
                <mesh
                  geometry={nodes.EXT_RIM_LF1_SUB0_EXT_METAL_RIM_0.geometry}
                  material={materials.EXT_METAL_RIM}
                  position={[-0.77, 0.29, 1.23]}
                />
              </group>
              <mesh
                geometry={nodes.EXT_TIRE_RF_2_EXT_RUBBER_TIRE_0.geometry}
                material={materials.EXT_RUBBER_TIRE}
              />
            </group>
            <group position={[-0.1, 0.09, 0.01]} rotation={[0.11, 0, 0.14]}>
              <group position={[0.77, -0.29, -1.71]}>
                <mesh
                  geometry={nodes.FR_DISKBRAKE_mesh_2_EXT_METAL_DISK_0.geometry}
                  material={materials.EXT_METAL_DISK}
                  position={[-0.75, 0.28, 1.71]}
                />
              </group>
            </group>
            <group position={[0.71, 0.06, -1.23]} rotation={[0.11, 0, 0.14]}>
              <mesh
                geometry={nodes.GEO_hub4_SUB1_GEO_hub1_0.geometry}
                material={materials.GEO_hub1}
                position={[-0.75, 0.28, 1.11]}
              />
              <mesh
                geometry={
                  nodes.GEO_hub4_SUB0_EXT_METAL_SHINY_EXHAUST_0.geometry
                }
                material={materials.EXT_METAL_SHINY_EXHAUST}
                position={[-0.7, 0.29, 1.22]}
              />
              <mesh
                geometry={nodes.GEO_hub4_SUB2_INT_METAL_BOLTS_0.geometry}
                material={materials.INT_METAL_BOLTS}
                position={[-0.72, 0.29, 1.19]}
              />
            </group>
            <group
              position={[-0.05, 0.21, 0.11]}
              rotation={[0.14, -0.15, 0.07]}
            >
              <mesh
                geometry={
                  nodes.susp_steering_arm_rf_2_EXT_METAL_SHINY_EXHAUST_0
                    .geometry
                }
                material={materials.EXT_METAL_SHINY_EXHAUST}
                position={[0.22, 0, 0]}
              />
            </group>
          </group>
          <group position={[0.67, 0.19, -1.29]} rotation={[0, 0, 0.16]}>
            <group position={[0.08, 0.1, -0.01]} rotation={[0, 0, -0.16]}>
              <group position={[-1.51, -0.01, 2.52]}>
                <mesh
                  geometry={nodes.RL_DISKBRAKE_mesh_2_EXT_METAL_DISK_0.geometry}
                  material={materials.EXT_METAL_DISK}
                  position={[1.5, 0.01, -2.52]}
                />
              </group>
            </group>
            <group position={[0.08, 0.1, -0.01]} rotation={[0, 0, -0.16]}>
              <group position={[-0.74, -0.3, 1.3]}>
                <mesh
                  geometry={
                    nodes.EXT_RIM_LR_SUB1_INT_PLASTIC_SW_BUTTONS_0.geometry
                  }
                  material={materials.INT_PLASTIC_SW_BUTTONS}
                  position={[0.87, 0.11, -1.36]}
                />
                <mesh
                  geometry={nodes.EXT_RIM_LR_SUB0_EXT_METAL_RIM_0.geometry}
                  material={materials.EXT_METAL_RIM}
                  position={[0.74, 0.3, -1.3]}
                />
              </group>
              <mesh
                geometry={nodes.EXT_TIRE_LR_2_EXT_RUBBER_TIRE_0.geometry}
                material={materials.EXT_RUBBER_TIRE}
              />
              <mesh
                geometry={nodes.GEO_rim3_SUB0_EXT_METAL_RIM_0.geometry}
                material={materials.EXT_METAL_RIM}
                position={[-0.71, 0, 0]}
              />
            </group>
            <group position={[-0.69, -0.08, 1.29]} rotation={[0, 0, -0.16]}>
              <mesh
                geometry={nodes.GEO_hub2_SUB1_GEO_hub1_0.geometry}
                material={materials.GEO_hub1}
                position={[0.74, 0.3, -1.18]}
              />
              <mesh
                geometry={
                  nodes.GEO_hub2_SUB0_EXT_METAL_SHINY_EXHAUST_0.geometry
                }
                material={materials.EXT_METAL_SHINY_EXHAUST}
                position={[0.64, 0.3, -1.32]}
              />
              <mesh
                geometry={nodes.GEO_hub2_SUB2_INT_METAL_BOLTS_0.geometry}
                material={materials.INT_METAL_BOLTS}
                position={[0.71, 0.3, -1.28]}
              />
            </group>
          </group>
          <group position={[-0.67, 0.19, -1.29]} rotation={[0, 0, -0.16]}>
            <group position={[-0.08, 0.1, -0.01]} rotation={[0, 0, 0.16]}>
              <group position={[0.74, -0.3, 0.82]}>
                <mesh
                  geometry={nodes.RR_DISKBRAKE_mesh_2_EXT_METAL_DISK_0.geometry}
                  material={materials.EXT_METAL_DISK}
                  position={[-0.73, 0.3, -0.82]}
                />
              </group>
            </group>
            <group position={[-0.08, 0.1, -0.01]} rotation={[0, 0, 0.16]}>
              <group position={[0.74, -0.3, 1.3]}>
                <mesh
                  geometry={
                    nodes.EXT_RIM_RR_SUB1_INT_PLASTIC_SW_BUTTONS_0.geometry
                  }
                  material={materials.INT_PLASTIC_SW_BUTTONS}
                  position={[-0.87, 0.11, -1.36]}
                />
                <mesh
                  geometry={nodes.EXT_RIM_RR_SUB0_EXT_METAL_RIM_0.geometry}
                  material={materials.EXT_METAL_RIM}
                  position={[-0.74, 0.3, -1.3]}
                />
              </group>
              <mesh
                geometry={nodes.EXT_TIRE_RR_2_EXT_RUBBER_TIRE_0.geometry}
                material={materials.EXT_RUBBER_TIRE}
              />
            </group>
            <group position={[0.69, -0.08, 1.29]} rotation={[0, 0, 0.16]}>
              <mesh
                geometry={nodes.GEO_hub3_SUB1_GEO_hub1_0.geometry}
                material={materials.GEO_hub1}
                position={[-0.74, 0.3, -1.18]}
              />
              <mesh
                geometry={
                  nodes.GEO_hub3_SUB0_EXT_METAL_SHINY_EXHAUST_0.geometry
                }
                material={materials.EXT_METAL_SHINY_EXHAUST}
                position={[-0.64, 0.3, -1.32]}
              />
              <mesh
                geometry={nodes.GEO_hub3_SUB2_INT_METAL_BOLTS_0.geometry}
                material={materials.INT_METAL_BOLTS}
                position={[-0.71, 0.3, -1.28]}
              />
            </group>
          </group>
          <group position={[0.24, 0.85, 0.37]} rotation={[-0.01, -0.02, -0.87]}>
            <group
              position={[0.48, -0.74, -0.86]}
              rotation={[-0.01, 0.02, 0.87]}
            >
              <mesh
                geometry={nodes.GEO_wind_L_2_EXT_LIGHTS_LENSES_FRONT_0.geometry}
                material={materials.EXT_LIGHTS_LENSES_FRONT}
                position={[0.38, 0.77, 0.48]}
              />
            </group>
            <group
              position={[0.48, -0.74, -0.86]}
              rotation={[-0.01, 0.02, 0.87]}
            >
              <mesh
                geometry={nodes.MIRROR_L_2_MIRROR_0.geometry}
                material={materials.MIRROR}
                position={[0.56, 0.74, 0.67]}
              />
            </group>
            <group
              position={[0.49, -0.74, -0.38]}
              rotation={[-0.01, 0.02, 0.87]}
            >
              <mesh
                geometry={nodes.GEO_DOOR_L_SUB3_EXT_PLASTIC_Black_0.geometry}
                material={materials.EXT_PLASTIC_Black}
                position={[0.44, 0.77, 0.03]}
              />
              <mesh
                geometry={nodes.GEO_DOOR_L_SUB2_EXT_PAINT_0.geometry}
                material={materials.EXT_PAINT}
                position={[0.28, 0.76, -0.02]}
              />
              <mesh
                geometry={
                  nodes.GEO_DOOR_L_SUB1_EXT_METAL_SHINY_EXHAUST_0.geometry
                }
                material={materials.EXT_METAL_SHINY_EXHAUST}
                position={[0.33, 0.75, 0.36]}
              />
              <mesh
                geometry={nodes.GEO_DOOR_L_SUB0_INT_METAL_BOLTS_0.geometry}
                material={materials.INT_METAL_BOLTS}
                position={[0.37, 0.78, -0.01]}
              />
              <mesh
                geometry={
                  nodes.GEO_INT_glass_L_2_EXT_LIGHTS_LENSES_FRONT_0.geometry
                }
                material={materials.EXT_LIGHTS_LENSES_FRONT}
                position={[0.38, 0.77, 0]}
              />
            </group>
            <group
              position={[0.49, -0.74, -0.38]}
              rotation={[-0.01, 0.02, 0.87]}
            >
              <mesh
                geometry={
                  nodes.polymsh_detached2_2_INT_PLASTIC_SW_BUTTONS_0.geometry
                }
                material={materials.INT_PLASTIC_SW_BUTTONS}
                position={[0.29, 0.88, -0.03]}
              />
            </group>
            <group
              position={[0.48, -0.74, -0.86]}
              rotation={[-0.01, 0.02, 0.87]}
            >
              <mesh
                geometry={
                  nodes.INT_MISC_DOOR_AO_L_2_INT_PLASTIC_SW_BUTTONS_0.geometry
                }
                material={materials.INT_PLASTIC_SW_BUTTONS}
                position={[0.27, 0.89, 0.24]}
              />
            </group>
            <group
              position={[0.49, -0.74, -0.38]}
              rotation={[-0.01, 0.02, 0.87]}
            >
              <mesh
                geometry={
                  nodes.polymsh_detached23_2_INT_AO_CARBON_FLAT_0.geometry
                }
                material={materials.INT_AO_CARBON_FLAT}
                position={[0.27, 0.76, -0.01]}
              />
            </group>
            <group
              position={[0.48, -0.74, -0.86]}
              rotation={[-0.01, 0.02, 0.87]}
            >
              <mesh
                geometry={nodes.INT_DOOR_L_BOLTS_2_INT_METAL_BOLTS_0.geometry}
                material={materials.INT_METAL_BOLTS}
                position={[0.37, 0.76, 0.47]}
              />
            </group>
          </group>
          <group
            position={[-0.24, 0.85, 0.37]}
            rotation={[-0.05, -0.02, -2.27]}
          >
            <group position={[0.48, 0.69, -0.9]} rotation={[-0.05, 0.02, 2.27]}>
              <mesh
                geometry={nodes.GEO_wind_R_2_EXT_LIGHTS_LENSES_FRONT_0.geometry}
                material={materials.EXT_LIGHTS_LENSES_FRONT}
                position={[-0.38, 0.77, 0.48]}
              />
            </group>
            <group position={[0.48, 0.69, -0.9]} rotation={[-0.05, 0.02, 2.27]}>
              <mesh
                geometry={nodes.MIRROR_R_2_MIRROR_0.geometry}
                material={materials.MIRROR}
                position={[-0.56, 0.74, 0.67]}
              />
            </group>
            <group
              position={[0.49, 0.72, -0.42]}
              rotation={[-0.05, 0.02, 2.27]}
            >
              <mesh
                geometry={nodes.GEO_DOOR_R_SUB3_EXT_PLASTIC_Black_0.geometry}
                material={materials.EXT_PLASTIC_Black}
                position={[-0.44, 0.77, 0.03]}
              />
              <mesh
                geometry={nodes.GEO_DOOR_R_SUB0_EXT_PAINT_0.geometry}
                material={materials.EXT_PAINT}
                position={[-0.28, 0.76, -0.02]}
              />
              <mesh
                geometry={
                  nodes.GEO_DOOR_R_SUB2_EXT_METAL_SHINY_EXHAUST_0.geometry
                }
                material={materials.EXT_METAL_SHINY_EXHAUST}
                position={[-0.33, 0.75, 0.36]}
              />
              <mesh
                geometry={nodes.GEO_DOOR_R_SUB1_INT_METAL_BOLTS_0.geometry}
                material={materials.INT_METAL_BOLTS}
                position={[-0.37, 0.78, -0.01]}
              />
              <mesh
                geometry={
                  nodes.GEO_INT_glass_L1_2_EXT_LIGHTS_LENSES_FRONT_0.geometry
                }
                material={materials.EXT_LIGHTS_LENSES_FRONT}
                position={[-0.38, 0.77, 0]}
              />
            </group>
            <group
              position={[0.49, 0.72, -0.42]}
              rotation={[-0.05, 0.02, 2.27]}
            >
              <mesh
                geometry={nodes.polymsh_detached3_2_EXT_RUBBER_TIRE_0.geometry}
                material={materials.EXT_RUBBER_TIRE}
                position={[-0.29, 0.88, -0.03]}
              />
            </group>
            <group position={[0.48, 0.69, -0.9]} rotation={[-0.05, 0.02, 2.27]}>
              <mesh
                geometry={
                  nodes.INT_MISC_DOOR_AP_R_2_INT_PLASTIC_SW_BUTTONS_0.geometry
                }
                material={materials.INT_PLASTIC_SW_BUTTONS}
                position={[-0.27, 0.89, 0.24]}
              />
            </group>
            <group
              position={[0.49, 0.72, -0.42]}
              rotation={[-0.05, 0.02, 2.27]}
            >
              <mesh
                geometry={
                  nodes.polymsh_detached24_2_INT_AO_CARBON_FLAT_0.geometry
                }
                material={materials.INT_AO_CARBON_FLAT}
                position={[-0.27, 0.76, -0.01]}
              />
            </group>
            <group position={[0.48, 0.69, -0.9]} rotation={[-0.05, 0.02, 2.27]}>
              <mesh
                geometry={nodes.INT_DOOR_R_BOLTS_2_INT_METAL_BOLTS_0.geometry}
                material={materials.INT_METAL_BOLTS}
                position={[-0.37, 0.76, 0.47]}
              />
            </group>
          </group>
          <group position={[-0.26, 0.18, 1.09]} rotation={[0, 0.22, 0]}>
            <group position={[0.49, -0.18, -1]} rotation={[0, -0.22, 0]}>
              <mesh
                geometry={
                  nodes.susp_arm_lf_low1_SUB0_EXT_METAL_SHINY_EXHAUST_0.geometry
                }
                material={materials.EXT_METAL_SHINY_EXHAUST}
                position={[-0.46, 0.19, 1.08]}
              />
              <mesh
                geometry={
                  nodes.susp_arm_lf_low1_SUB1_INT_METAL_BOLTS_0.geometry
                }
                material={materials.INT_METAL_BOLTS}
                position={[-0.64, 0.2, 1.23]}
              />
            </group>
            <group position={[-0.4, 0.02, 0.06]} rotation={[0.01, -0.45, 0.46]}>
              <group
                position={[0.22, -0.34, -1.34]}
                rotation={[0.09, 0.21, -0.46]}
              >
                <mesh
                  geometry={
                    nodes.susp_shock_rf_2_EXT_METAL_SHINY_EXHAUST_0.geometry
                  }
                  material={materials.EXT_METAL_SHINY_EXHAUST}
                  position={[-0.41, 0.32, 1.29]}
                />
              </group>
            </group>
          </group>
          <group position={[0, 0, -0.48]}>
            <mesh
              geometry={nodes.black_shiny_2_EXT_RUBBER_TIRE_0.geometry}
              material={materials.EXT_RUBBER_TIRE}
              position={[-0.07, 0.52, -0.79]}
            />
          </group>
          <group position={[0, 0, -0.48]}>
            <mesh
              geometry={nodes.LIGHT_RAIN_2_EXT_LIGHTS_CHROME_0.geometry}
              material={materials.EXT_LIGHTS_CHROME}
              position={[0, 0.32, -1.55]}
            />
          </group>
          <group position={[-0.13, 0.39, -1.15]} rotation={[0, -0.26, 0]}>
            <group
              position={[0.09, 0.03, 0]}
              rotation={[Math.PI / 2, 0, -Math.PI / 2]}
            >
              <group
                position={[0.42, 0.34, 1.07]}
                rotation={[-0.26, 0, Math.PI / 2]}
              >
                <mesh
                  geometry={
                    nodes.polymsh_detached12_2_EXT_METAL_SHINY_EXHAUST_0
                      .geometry
                  }
                  material={materials.EXT_METAL_SHINY_EXHAUST}
                  position={[-0.05, 0.33, -1.12]}
                />
              </group>
            </group>
            <group position={[0.42, -0.39, 1.07]} rotation={[0, 0.26, 0]}>
              <mesh
                geometry={
                  nodes.polymsh_detached10_SUB0_EXT_METAL_SHINY_EXHAUST_0
                    .geometry
                }
                material={materials.EXT_METAL_SHINY_EXHAUST}
                position={[-0.11, 0.42, -1.14]}
              />
              <mesh
                geometry={
                  nodes.polymsh_detached10_SUB1_INT_METAL_BOLTS_0.geometry
                }
                material={materials.INT_METAL_BOLTS}
                position={[-0.11, 0.43, -1.14]}
              />
            </group>
          </group>
          <group position={[0, 0, -0.48]}>
            <mesh
              geometry={
                nodes.EXT_shiny_black3_2_EXT_METAL_SHINY_EXHAUST_0.geometry
              }
              material={materials.EXT_METAL_SHINY_EXHAUST}
              position={[0, 0.74, 1.1]}
            />
          </group>
          <group position={[0.14, 0.17, -1.1]} rotation={[0, 0.16, 0]}>
            <group position={[0.49, 0.04, -0.09]} rotation={[0.04, 0.07, 2.67]}>
              <group
                position={[0.72, 0.56, 1.1]}
                rotation={[-0.08, 0.22, -2.66]}
              >
                <mesh
                  geometry={
                    nodes.susp_shock_lr_2_EXT_METAL_SHINY_EXHAUST_0.geometry
                  }
                  material={materials.EXT_METAL_SHINY_EXHAUST}
                  position={[0.39, 0.33, -1.21]}
                />
              </group>
            </group>
            <group position={[-0.32, -0.17, 1.07]} rotation={[0, -0.16, 0]}>
              <mesh
                geometry={
                  nodes.susp_arm_lr_low_SUB0_EXT_METAL_SHINY_EXHAUST_0.geometry
                }
                material={materials.EXT_METAL_SHINY_EXHAUST}
                position={[0.39, 0.19, -1.12]}
              />
              <mesh
                geometry={nodes.susp_arm_lr_low_SUB1_INT_METAL_BOLTS_0.geometry}
                material={materials.INT_METAL_BOLTS}
                position={[0.61, 0.21, -1.27]}
              />
            </group>
          </group>
          <group position={[0, 0, -0.48]}>
            <mesh
              geometry={nodes.EXT_DISK_LF1_2_EXT_MISC_GLOSSY_0.geometry}
              material={materials.EXT_MISC_GLOSSY}
              position={[0, 0.38, 0.05]}
            />
          </group>
          <group position={[-0.12, 0.26, -1.3]}>
            <group position={[0.12, -0.26, 1.3]}>
              <mesh
                geometry={
                  nodes.shaft_left1_2_EXT_METAL_SHINY_EXHAUST_0.geometry
                }
                material={materials.EXT_METAL_SHINY_EXHAUST}
                position={[-0.35, 0.28, -1.3]}
              />
            </group>
          </group>
          <group position={[0.1, 0.35, -1.3]} rotation={[0, 0.08, 0]}>
            <group rotation={[0, -0.08, 0]}>
              <mesh
                geometry={
                  nodes.susp_arm_lr_up_2_EXT_METAL_SHINY_EXHAUST_0.geometry
                }
                material={materials.EXT_METAL_SHINY_EXHAUST}
                position={[0.26, 0.03, 0]}
              />
            </group>
          </group>
          <group position={[0.13, 0.39, -1.15]} rotation={[0, 0.26, 0]}>
            <group
              position={[-0.09, 0.03, 0]}
              rotation={[Math.PI / 2, 0, -Math.PI / 2]}
            >
              <group
                position={[0.42, -0.34, 1.07]}
                rotation={[0.26, 0, Math.PI / 2]}
              >
                <mesh
                  geometry={
                    nodes.polymsh_detached13_2_EXT_METAL_SHINY_EXHAUST_0
                      .geometry
                  }
                  material={materials.EXT_METAL_SHINY_EXHAUST}
                  position={[0.05, 0.33, -1.12]}
                />
              </group>
            </group>
            <group position={[-0.42, -0.39, 1.07]} rotation={[0, -0.26, 0]}>
              <mesh
                geometry={
                  nodes.polymsh_detached11_SUB0_EXT_METAL_SHINY_EXHAUST_0
                    .geometry
                }
                material={materials.EXT_METAL_SHINY_EXHAUST}
                position={[0.11, 0.42, -1.14]}
              />
              <mesh
                geometry={
                  nodes.polymsh_detached11_SUB1_INT_METAL_BOLTS_0.geometry
                }
                material={materials.INT_METAL_BOLTS}
                position={[0.11, 0.43, -1.14]}
              />
            </group>
          </group>
          <group position={[0, 0, -0.48]}>
            <mesh
              geometry={nodes.red_glossy_2_EXT_METAL_SHINY_EXHAUST_0.geometry}
              material={materials.EXT_METAL_SHINY_EXHAUST}
              position={[0.18, 0.31, 0.45]}
            />
          </group>
          <group position={[0, 0, -0.48]}>
            <mesh
              geometry={
                nodes.GEO_Front_light_Chrome_2_EXT_LIGHTS_CHROME_0.geometry
              }
              material={materials.EXT_LIGHTS_CHROME}
              position={[0, 0.43, 2.07]}
            />
          </group>
          <group position={[-0.29, 0.34, 1.06]} rotation={[0, 0.2, 0]}>
            <group position={[0.5, -0.34, -0.98]} rotation={[0, -0.2, 0]}>
              <mesh
                geometry={
                  nodes.susp_arm_rf_up_2_EXT_METAL_SHINY_EXHAUST_0.geometry
                }
                material={materials.EXT_METAL_SHINY_EXHAUST}
                position={[-0.46, 0.36, 1.05]}
              />
            </group>
          </group>
          <group position={[-0.2, 0.44, 1.28]} rotation={[-2.76, -0.01, 2.68]}>
            <group
              position={[0.2, -0.89, 1.02]}
              rotation={[-2.79, -0.15, 2.71]}
            >
              <mesh
                geometry={
                  nodes.polymsh_extracted1_2_EXT_METAL_SHINY_EXHAUST_0.geometry
                }
                material={materials.EXT_METAL_SHINY_EXHAUST}
                position={[-0.14, 0.46, 1.3]}
              />
            </group>
          </group>
          <group position={[-0.1, 0.35, -1.3]} rotation={[0, -0.08, 0]}>
            <group position={[0.2, -0.35, 1.28]} rotation={[0, 0.08, 0]}>
              <mesh
                geometry={
                  nodes.susp_arm_lr_up1_2_EXT_METAL_SHINY_EXHAUST_0.geometry
                }
                material={materials.EXT_METAL_SHINY_EXHAUST}
                position={[-0.37, 0.37, -1.3]}
              />
            </group>
          </group>
          <group position={[0.12, 0.26, -1.3]}>
            <group position={[-0.12, -0.26, 1.3]}>
              <mesh
                geometry={nodes.shaft_left_2_EXT_METAL_SHINY_EXHAUST_0.geometry}
                material={materials.EXT_METAL_SHINY_EXHAUST}
                position={[0.35, 0.28, -1.3]}
              />
            </group>
          </group>
          <group position={[0, 0, -0.48]}>
            <mesh
              geometry={
                nodes.susp_stationary_2_EXT_METAL_SHINY_EXHAUST_0.geometry
              }
              material={materials.EXT_METAL_SHINY_EXHAUST}
              position={[0, 0.26, 0.54]}
            />
          </group>
          <group position={[0.29, 0.34, 1.06]} rotation={[0, -0.2, 0]}>
            <group position={[0, 0, -0.06]} rotation={[0, 0.2, 0]}>
              <mesh
                geometry={
                  nodes.susp_arm_lf_up_2_EXT_METAL_SHINY_EXHAUST_0.geometry
                }
                material={materials.EXT_METAL_SHINY_EXHAUST}
                position={[0.16, 0.02, 0.04]}
              />
            </group>
          </group>
          <group position={[0, 0, -0.48]}>
            <mesh
              geometry={nodes.EXT_kevlar_flat_2_INT_AO_CARBON_FLAT_0.geometry}
              material={materials.INT_AO_CARBON_FLAT}
              position={[0, 0.48, 0.54]}
            />
          </group>
          <group position={[0, 0, -0.48]}>
            <mesh
              geometry={nodes.black_2_EXT_RUBBER_TIRE_0.geometry}
              material={materials.EXT_RUBBER_TIRE}
              position={[0, 0.44, 1.79]}
            />
          </group>
          <group position={[0, 0.63, 0.99]} rotation={[-2.78, 0.67, Math.PI]}>
            <group
              position={[0.34, -0.06, 0.04]}
              rotation={[-0.02, -0.08, -0.32]}
            >
              <group
                position={[0.44, -0.79, -0.51]}
                rotation={[-0.17, -0.84, 0.1]}
              >
                <mesh
                  geometry={
                    nodes.polymsh_detached20_2_EXT_PLASTIC_Black_0.geometry
                  }
                  material={materials.EXT_PLASTIC_Black}
                  position={[0.25, 0.65, 0.74]}
                />
              </group>
            </group>
            <group
              position={[0.52, -0.95, -0.44]}
              rotation={[-0.56, -0.79, -0.42]}
            >
              <mesh
                geometry={nodes.wiper_SUB0_EXT_PLASTIC_Black_0.geometry}
                material={materials.EXT_PLASTIC_Black}
                position={[0.13, 0.65, 0.86]}
              />
              <mesh
                geometry={nodes.wiper_SUB1_INT_METAL_BOLTS_0.geometry}
                material={materials.INT_METAL_BOLTS}
                position={[0, 0.63, 0.99]}
              />
            </group>
          </group>
          <group position={[0.26, 0.18, 1.09]} rotation={[0, -0.22, 0]}>
            <group position={[-0.49, -0.18, -1]} rotation={[0, 0.22, 0]}>
              <mesh
                geometry={
                  nodes.susp_arm_lf_low_SUB0_EXT_METAL_SHINY_EXHAUST_0.geometry
                }
                material={materials.EXT_METAL_SHINY_EXHAUST}
                position={[0.46, 0.19, 1.08]}
              />
              <mesh
                geometry={nodes.susp_arm_lf_low_SUB1_INT_METAL_BOLTS_0.geometry}
                material={materials.INT_METAL_BOLTS}
                position={[0.64, 0.2, 1.23]}
              />
            </group>
            <group position={[0.4, 0.02, 0.06]} rotation={[1.28, -0.36, 2.61]}>
              <group
                position={[0.21, 1.37, 0.21]}
                rotation={[1.38, 0.21, -2.68]}
              >
                <mesh
                  geometry={
                    nodes.susp_shock_lf_2_EXT_METAL_SHINY_EXHAUST_0.geometry
                  }
                  material={materials.EXT_METAL_SHINY_EXHAUST}
                  position={[0.41, 0.32, 1.29]}
                />
              </group>
            </group>
          </group>
          <group position={[-0.14, 0.17, -1.1]} rotation={[0, -0.16, 0]}>
            <group
              position={[-0.49, 0.04, -0.09]}
              rotation={[0.04, -0.07, 0.47]}
            >
              <group
                position={[0.72, -0.56, 1.1]}
                rotation={[0.08, 0.22, -0.48]}
              >
                <mesh
                  geometry={
                    nodes.susp_shock_lr1_2_EXT_METAL_SHINY_EXHAUST_0.geometry
                  }
                  material={materials.EXT_METAL_SHINY_EXHAUST}
                  position={[-0.39, 0.33, -1.21]}
                />
              </group>
            </group>
            <group position={[0.32, -0.17, 1.07]} rotation={[0, 0.16, 0]}>
              <mesh
                geometry={
                  nodes.susp_arm_lr_low1_SUB0_EXT_METAL_SHINY_EXHAUST_0.geometry
                }
                material={materials.EXT_METAL_SHINY_EXHAUST}
                position={[-0.39, 0.19, -1.12]}
              />
              <mesh
                geometry={
                  nodes.susp_arm_lr_low1_SUB1_INT_METAL_BOLTS_0.geometry
                }
                material={materials.INT_METAL_BOLTS}
                position={[-0.61, 0.21, -1.27]}
              />
            </group>
          </group>
          <group position={[0, 0, -0.48]}>
            <mesh
              geometry={nodes.rearlights_bulbs_2_EXT_LIGHTS_CHROME_0.geometry}
              material={materials.EXT_LIGHTS_CHROME}
              position={[0, 0.63, -1.12]}
            />
          </group>
          <group position={[0.2, 0.44, 1.28]} rotation={[-2.76, -0.01, -2.55]}>
            <group
              position={[-0.34, -0.84, 1.03]}
              rotation={[-2.83, 0.22, -2.59]}
            >
              <mesh
                geometry={
                  nodes.polymsh_detached_2_EXT_METAL_SHINY_EXHAUST_0.geometry
                }
                material={materials.EXT_METAL_SHINY_EXHAUST}
                position={[0.14, 0.46, 1.3]}
              />
            </group>
          </group>
          <group position={[0, 0, -0.48]}>
            <mesh
              geometry={nodes.headlights_blacl_2_EXT_LIGHTS_2_0.geometry}
              material={materials.EXT_LIGHTS_2}
              position={[0, 0.51, 0.5]}
            />
          </group>
          <group position={[0, 0, -0.48]}>
            <mesh
              geometry={
                nodes.frontlights_lens_2_EXT_LIGHTS_LENSES_FRONT_0.geometry
              }
              material={materials.EXT_LIGHTS_LENSES_FRONT}
              position={[0, 0.46, 2.06]}
            />
          </group>
          <group position={[0, 0, -0.48]}>
            <mesh
              geometry={nodes.Default_2_EXT_METAL_SHINY_EXHAUST_0.geometry}
              material={materials.EXT_METAL_SHINY_EXHAUST}
              position={[0, 0.26, -0.82]}
            />
          </group>
          <group position={[0, 0.82, -1.81]}>
            <mesh
              geometry={nodes.EXT_PAINT_WING_SUB1_EXT_PAINT_wing_0.geometry}
              material={materials.EXT_PAINT_wing}
              position={[0, 0.01, -0.08]}
            />
            <mesh
              geometry={nodes.EXT_PAINT_WING_SUB0_INT_METAL_BOLTS_0.geometry}
              material={materials.INT_METAL_BOLTS}
              position={[0, 0.01, -0.05]}
            />
          </group>
          <group position={[0, 0, -0.48]}>
            <mesh
              geometry={nodes.BLOTS_2_INT_METAL_BOLTS_0.geometry}
              material={materials.INT_METAL_BOLTS}
              position={[0, 0.48, 0.29]}
            />
          </group>
          <group position={[0, 0, -0.48]}>
            <mesh
              geometry={
                nodes.INT_MISC_PLASIC_2_INT_PLASTIC_SW_BUTTONS_0.geometry
              }
              material={materials.INT_PLASTIC_SW_BUTTONS}
              position={[-0.04, 0.53, 0.92]}
            />
          </group>
          <group position={[0, 0, -0.48]}>
            <mesh
              geometry={
                nodes.INT_MISC_AO_METAL_2_INT_PLASTIC_SW_BUTTONS_0.geometry
              }
              material={materials.INT_PLASTIC_SW_BUTTONS}
              position={[0.04, 0.69, 0.65]}
            />
          </group>
          <group position={[0, 0, -0.48]}>
            <mesh
              geometry={
                nodes.INT_MISC_RUBBER_2_INT_AO_RUBBER_GRIP_SW_0.geometry
              }
              material={materials.INT_AO_RUBBER_GRIP_SW}
              position={[0, 0.76, 0.46]}
            />
          </group>
          <group position={[0, 0, -0.48]}>
            <mesh
              geometry={nodes.INT_FUEL_HOSE_2_INT_Fuel_pipe_0.geometry}
              material={materials.INT_Fuel_pipe}
              position={[0.29, 0.49, 0.1]}
            />
          </group>
          <group position={[0.09, 0.54, 0.41]} rotation={[0.17, -0.1, 0]}>
            <group position={[-0.12, -0.6, -0.3]} rotation={[-0.18, 0.1, 0.02]}>
              <mesh
                geometry={nodes.RPM_LED0_2_INT_PLASTIC_SW_BUTTONS_0.geometry}
                material={materials.INT_PLASTIC_SW_BUTTONS}
                position={[0.13, 0.65, 0.36]}
              />
            </group>
            <group position={[-0.13, -0.6, -0.3]} rotation={[-0.18, 0.1, 0.02]}>
              <mesh
                geometry={nodes.RPM_LED1_2_INT_PLASTIC_SW_BUTTONS_0.geometry}
                material={materials.INT_PLASTIC_SW_BUTTONS}
                position={[0.13, 0.65, 0.36]}
              />
            </group>
            <group position={[-0.14, -0.6, -0.3]} rotation={[-0.18, 0.1, 0.02]}>
              <mesh
                geometry={nodes.RPM_LED2_2_INT_PLASTIC_SW_BUTTONS_0.geometry}
                material={materials.INT_PLASTIC_SW_BUTTONS}
                position={[0.13, 0.65, 0.36]}
              />
            </group>
            <group position={[-0.15, -0.6, -0.3]} rotation={[-0.18, 0.1, 0.02]}>
              <mesh
                geometry={nodes.RPM_LED3_2_INT_PLASTIC_SW_BUTTONS_0.geometry}
                material={materials.INT_PLASTIC_SW_BUTTONS}
                position={[0.13, 0.65, 0.36]}
              />
            </group>
            <group position={[-0.16, -0.6, -0.3]} rotation={[-0.18, 0.1, 0.02]}>
              <mesh
                geometry={nodes.RPM_LED4_2_INT_PLASTIC_SW_BUTTONS_0.geometry}
                material={materials.INT_PLASTIC_SW_BUTTONS}
                position={[0.13, 0.65, 0.36]}
              />
            </group>
            <group position={[-0.17, -0.6, -0.3]} rotation={[-0.18, 0.1, 0.02]}>
              <mesh
                geometry={nodes.RPM_LED5_2_INT_PLASTIC_SW_BUTTONS_0.geometry}
                material={materials.INT_PLASTIC_SW_BUTTONS}
                position={[0.13, 0.65, 0.36]}
              />
            </group>
            <group position={[-0.18, -0.6, -0.3]} rotation={[-0.18, 0.1, 0.02]}>
              <mesh
                geometry={nodes.RPM_LED6_2_INT_PLASTIC_SW_BUTTONS_0.geometry}
                material={materials.INT_PLASTIC_SW_BUTTONS}
                position={[0.13, 0.65, 0.36]}
              />
            </group>
            <group position={[-0.19, -0.6, -0.3]} rotation={[-0.18, 0.1, 0.02]}>
              <mesh
                geometry={nodes.RPM_LED7_2_INT_PLASTIC_SW_BUTTONS_0.geometry}
                material={materials.INT_PLASTIC_SW_BUTTONS}
                position={[0.13, 0.65, 0.36]}
              />
            </group>
            <group position={[-0.07, 0.01, -0.02]} rotation={[0, 0, -0.17]}>
              <group position={[0, 0, -0.01]}>
                <mesh
                  geometry={
                    nodes.polymsh_detached6_2_INT_AO_CARBON_SHINY_0.geometry
                  }
                  material={materials.INT_AO_CARBON_SHINY}
                  position={[-0.02, 0, 0.01]}
                />
              </group>
            </group>
            <group
              position={[0.07, 0.01, -0.02]}
              rotation={[-0.01, 0.02, 0.17]}
            >
              <group position={[0, 0, -0.01]}>
                <mesh
                  geometry={
                    nodes.INT_SW_CARBON_PEDAL_2_INT_AO_CARBON_SHINY_0.geometry
                  }
                  material={materials.INT_AO_CARBON_SHINY}
                  position={[0.02, 0, 0.01]}
                />
              </group>
            </group>
            <group position={[-0.12, -0.6, -0.3]} rotation={[-0.18, 0.1, 0.02]}>
              <mesh
                geometry={
                  nodes.GEO_Steer_HR_SUB3_INT_PLASTIC_SW_BUTTONS_0.geometry
                }
                material={materials.INT_PLASTIC_SW_BUTTONS}
                position={[0.1, 0.6, 0.34]}
              />
              <mesh
                geometry={
                  nodes.GEO_Steer_HR_SUB1_INT_AO_RUBBER_GRIP_SW_0.geometry
                }
                material={materials.INT_AO_RUBBER_GRIP_SW}
                position={[0.1, 0.56, 0.34]}
              />
              <mesh
                geometry={
                  nodes.GEO_Steer_HR_SUB6_INT_AO_CARBON_SHINY_0.geometry
                }
                material={materials.INT_AO_CARBON_SHINY}
                position={[0.1, 0.61, 0.35]}
              />
              <mesh
                geometry={nodes.GEO_Steer_HR_SUB0_INT_AO_METAL_SW_0.geometry}
                material={materials.INT_AO_METAL_SW}
                position={[0.1, 0.57, 0.37]}
              />
              <mesh
                geometry={
                  nodes.GEO_Steer_HR_SUB2_INT_PLASTIC_SW_BUTTONS_0.geometry
                }
                material={materials.INT_PLASTIC_SW_BUTTONS}
                position={[0.1, 0.58, 0.36]}
              />
              <mesh
                geometry={
                  nodes.GEO_Steer_HR_SUB4_INT_PLASTIC_SW_BUTTONS_0.geometry
                }
                material={materials.INT_PLASTIC_SW_BUTTONS}
                position={[0.1, 0.58, 0.34]}
              />
              <mesh
                geometry={nodes.GEO_Steer_HR_SUB5_INT_METAL_BOLTS_0.geometry}
                material={materials.INT_METAL_BOLTS}
                position={[0.1, 0.59, 0.34]}
              />
            </group>
            <mesh
              geometry={nodes.GEO_LCD_2_LCD_0.geometry}
              material={materials.material}
              position={[0, 0.06, -0.07]}
            />
          </group>
          <group position={[0, 0, -0.48]}>
            <mesh
              geometry={nodes.INT_BLOTS_2_INT_METAL_BOLTS_0.geometry}
              material={materials.INT_METAL_BOLTS}
              position={[-0.03, 0.51, 0.92]}
            />
          </group>
          <group position={[-0.03, 0, 0]} scale={[1.2, 1, 1]}>
            <mesh
              geometry={nodes.GEO_pillow_SUB1_INT_Alcantara_0.geometry}
              material={materials.INT_Alcantara}
              position={[0.15, 0.69, -0.26]}
            />
            <mesh
              geometry={nodes.GEO_pillow_SUB2_INT_Stich_0.geometry}
              material={materials.INT_Stich}
              position={[0.15, 0.7, -0.25]}
            />
            <mesh
              geometry={nodes.GEO_pillow_SUB0_INT_PLASTIC_SW_BUTTONS_0.geometry}
              material={materials.INT_PLASTIC_SW_BUTTONS}
              position={[0.15, 0.69, -0.32]}
            />
          </group>
          <mesh
            geometry={nodes.CINTURE_ON_SUB1_INT_BELT_TEXTILE_0.geometry}
            material={materials.INT_BELT_TEXTILE}
            position={[0.16, 0.34, -0.07]}
          />
          <mesh
            geometry={nodes.CINTURE_ON_SUB2_INT_BELT_LOGO_0.geometry}
            material={materials.INT_BELT_LOGO}
            position={[0.15, 0.56, -0.06]}
          />
          <mesh
            geometry={nodes.CINTURE_ON_SUB0_INT_PLASTIC_SW_BUTTONS_0.geometry}
            material={materials.INT_PLASTIC_SW_BUTTONS}
            position={[0.16, 0.36, 0.1]}
          />
          <mesh
            geometry={nodes.GEO_Cables_SUB0_INT_PLASTIC_SW_BUTTONS_0.geometry}
            material={materials.INT_PLASTIC_SW_BUTTONS}
            position={[-0.03, 0.51, 0.44]}
          />
          <mesh
            geometry={nodes.GEO_Cables_SUB1_INT_PLASTIC_SW_BUTTONS_0.geometry}
            material={materials.INT_PLASTIC_SW_BUTTONS}
            position={[0.07, 0.71, 0.05]}
          />
          <mesh
            geometry={
              nodes.polymsh_detached19_SUB1_INT_PLASTIC_SW_BUTTONS_0.geometry
            }
            material={materials.INT_PLASTIC_SW_BUTTONS}
            position={[-0.05, 0.49, 0.47]}
          />
          <mesh
            geometry={
              nodes.polymsh_detached19_SUB0_INT_Loghi_NM_Cavo_torciglione_0
                .geometry
            }
            material={materials.INT_Loghi_NM_Cavo_torciglione}
            position={[0.15, 0.51, 0.47]}
          />
          <mesh
            geometry={nodes.GEO_Metal_2_INT_PLASTIC_SW_BUTTONS_0.geometry}
            material={materials.INT_PLASTIC_SW_BUTTONS}
            position={[0, 0.18, 0.61]}
          />
          <mesh
            geometry={nodes.CINTURE_OFF_SUB0_INT_BELT_TEXTILE_0.geometry}
            material={materials.INT_BELT_TEXTILE}
            position={[0.15, 0.3, 0.07]}
          />
          <mesh
            geometry={nodes.CINTURE_OFF_SUB2_INT_BELT_LOGO_0.geometry}
            material={materials.INT_BELT_LOGO}
            position={[0.15, 0.38, -0.19]}
          />
          <mesh
            geometry={nodes.CINTURE_OFF_SUB1_INT_PLASTIC_SW_BUTTONS_0.geometry}
            material={materials.INT_PLASTIC_SW_BUTTONS}
            position={[0.15, 0.2, 0.19]}
          />
          <mesh
            geometry={nodes.GEO_Cockpit_HR_SUB4_INT_AO_CARBON_SHINY_0.geometry}
            material={materials.INT_AO_CARBON_SHINY}
            position={[0.15, 0.32, 0.14]}
          />
          <mesh
            geometry={nodes.GEO_Cockpit_HR_SUB0_INT_AO_CARBON_SHINY_0.geometry}
            material={materials.INT_AO_CARBON_SHINY}
            position={[0, 0.5, 0.34]}
          />
          <mesh
            geometry={nodes.GEO_Cockpit_HR_SUB2_INT_AO_CARBON_FLAT_0.geometry}
            material={materials.INT_AO_CARBON_FLAT}
            position={[0, 0.51, 0.45]}
          />
          <mesh
            geometry={nodes.GEO_Cockpit_HR_SUB3_INT_AO_METAL_BLACK_0.geometry}
            material={materials.INT_AO_METAL_BLACK}
            position={[-0.05, 0.39, 0.12]}
          />
          <mesh
            geometry={nodes.GEO_Cockpit_HR_SUB1_INT_AO_METAL_BLACK_0.geometry}
            material={materials.INT_AO_METAL_BLACK}
            position={[0, 0.49, 0.88]}
          />
          <mesh
            geometry={nodes.EXT_chrome_2_EXT_METAL_SHINY_EXHAUST_0.geometry}
            material={materials.EXT_METAL_SHINY_EXHAUST}
            position={[0, 0.49, -0.1]}
          />
          <mesh
            geometry={
              nodes.GEO_Windscreen_SUB0_EXT_LIGHTS_LENSES_FRONT_0.geometry
            }
            material={materials.EXT_LIGHTS_LENSES_FRONT}
            position={[0, 0.72, 0.62]}
          />
          <mesh
            geometry={nodes.GEO_Windscreen_SUB1_INT_windscreen_Black_0.geometry}
            material={materials.INT_windscreen_Black}
            position={[0, 0.83, 0.47]}
          />
          <mesh
            geometry={
              nodes.GEO_Windscreen_SUB2_INT_PLASTIC_SW_BUTTONS_0.geometry
            }
            material={materials.INT_PLASTIC_SW_BUTTONS}
            position={[0, 0.74, 0.62]}
          />
          <mesh
            geometry={nodes.FRONT_LIGHT1_2_EXT_LIGHTS_CHROME_0.geometry}
            material={materials.EXT_LIGHTS_CHROME}
            position={[0, 0.41, 1.62]}
          />
          <mesh
            geometry={nodes.FRONT_LIGHT3_2_EXT_LIGHTS_CHROME_0.geometry}
            material={materials.EXT_LIGHTS_CHROME}
            position={[0, 0.52, 1.5]}
          />
          <mesh
            geometry={nodes.EXT_carbon_shiny_2_INT_AO_CARBON_FLAT_0.geometry}
            material={materials.INT_AO_CARBON_FLAT}
            position={[0, 0.49, 0.07]}
          />
          <mesh
            geometry={nodes.FRONT_LIGHT2_2_EXT_LIGHTS_CHROME_0.geometry}
            material={materials.EXT_LIGHTS_CHROME}
            position={[0, 0.46, 1.57]}
          />
          <mesh
            geometry={nodes.rearlights_Glass_2_EXT_LIGHTS_CHROME_0.geometry}
            material={materials.EXT_LIGHTS_CHROME}
            position={[0, 0.63, -1.61]}
          />
          <mesh
            geometry={nodes.GEO_Cockpit_LR_SUB0_INT_BELT_TEXTILE_0.geometry}
            material={materials.INT_BELT_TEXTILE}
            position={[0.15, 0.48, -0.1]}
          />
          <mesh
            geometry={nodes.GEO_Cockpit_LR_SUB1_INT_BELT_LOGO_0.geometry}
            material={materials.INT_BELT_LOGO}
            position={[0.15, 0.56, -0.06]}
          />
          <mesh
            geometry={nodes.GEO_Cockpit_LR_SUB3_INT_AO_METAL_BLACK_0.geometry}
            material={materials.INT_AO_METAL_BLACK}
            position={[0, 0.74, 0.62]}
          />
          <mesh
            geometry={nodes.GEO_Cockpit_LR_SUB2_INT_AO_CARBON_SHINY_0.geometry}
            material={materials.INT_AO_CARBON_SHINY}
            position={[0, 0.51, 0.46]}
          />
          <mesh
            geometry={nodes.GEO_Cockpit_LR_SUB4_INT_METAL_BOLTS_0.geometry}
            material={materials.INT_METAL_BOLTS}
            position={[0, 0.64, 0.87]}
          />
          <mesh
            geometry={nodes.grid_SUB0_EXT_METAL_GRID_0.geometry}
            material={materials.EXT_METAL_GRID}
            position={[0, 0.39, 0.25]}
          />
          <mesh
            geometry={nodes.grid_SUB1_EXT_METAL_SHINY_EXHAUST_0.geometry}
            material={materials.EXT_METAL_SHINY_EXHAUST}
            position={[0, 0.39, 0.25]}
          />
          <group position={[0, 0, -0.48]}>
            <mesh
              geometry={nodes.polymsh_detached5_2_EXT_PAINT_0.geometry}
              material={materials.EXT_PAINT}
              position={[0, 0.28, 2.15]}
            />
          </group>
          <mesh
            geometry={nodes.EXT_PAINT_SUB2_EXT_PLASTIC_Black_0.geometry}
            material={materials.EXT_PLASTIC_Black}
            position={[0, 0.74, 0.58]}
          />
          <mesh
            geometry={nodes.EXT_PAINT_SUB1_EXT_LIGHTS_LENSES_FRONT_0.geometry}
            material={materials.EXT_LIGHTS_LENSES_FRONT}
            position={[0, 0.74, 0.62]}
          />
          <mesh
            geometry={nodes.EXT_PAINT_SUB0_EXT_PAINT_0.geometry}
            material={materials.EXT_PAINT}
            position={[0, 0.52, 0.09]}
          />
          <mesh
            geometry={nodes.GEO_Engine_SUB1_EXT_METAL_SHINY_EXHAUST_0.geometry}
            material={materials.EXT_METAL_SHINY_EXHAUST}
            position={[0, 0.54, -1.62]}
          />
          <mesh
            geometry={nodes.GEO_Engine_SUB0_EXT_METAL_FLAT_0.geometry}
            material={materials.EXT_METAL_FLAT}
            position={[-0.01, 0.41, -1.13]}
          />
          <mesh
            geometry={
              nodes.EXT_shiny_black_SUB1_EXT_LIGHTS_LENSES_FRONT_0.geometry
            }
            material={materials.EXT_LIGHTS_LENSES_FRONT}
            position={[0, 0.44, -0.14]}
          />
          <mesh
            geometry={
              nodes.EXT_shiny_black_SUB0_EXT_METAL_SHINY_EXHAUST_0.geometry
            }
            material={materials.EXT_METAL_SHINY_EXHAUST}
            position={[0, 0.49, -0.13]}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/car-transformed.glb");
