/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 shoe.gltf --transform
Author: Nevena Knežević (https://sketchfab.com/gavez)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/old-shoe-394abb35c7ef4c08bfb64778864d6410
Title: Old shoe
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/shoe-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <group position={[0, 1.13, 21.31]} rotation={[Math.PI / 2, 0, 0]}>
        <group position={[-2.58, -11.7, -0.3]}>
          <mesh
            geometry={nodes.Object_2.geometry}
            material={materials.material_0}
          />
          <mesh
            geometry={nodes.Object_3.geometry}
            material={materials.material_0}
          />
          <mesh
            geometry={nodes.Object_4.geometry}
            material={materials.material_0}
          />
          <mesh
            geometry={nodes.Object_5.geometry}
            material={materials.material_0}
          />
          <mesh
            geometry={nodes.Object_6.geometry}
            material={materials.material_0}
          />
          <mesh
            geometry={nodes.Object_7.geometry}
            material={materials.material_0}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/shoe-transformed.glb");
