/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 tablet.gltf --transform
Author: Artem (https://sketchfab.com/Artem_Tolstolytskii)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/graphic-tablet-free-1d71ac4c5b5f4a0190ac01266c153417
Title: Graphic Tablet Free
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/tablet-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group
          position={[1.79, 0.72, 0.69]}
          rotation={[-1.58, 0.01, -2.39]}
          scale={0.38}
        >
          <mesh
            geometry={nodes.polySurface3_blinn2_0.geometry}
            material={materials.blinn2}
          />
          <mesh
            geometry={nodes.polySurface9_blinn3_0.geometry}
            material={materials.blinn3}
          />
          <mesh
            geometry={nodes.polySurface11_blinn1_0.geometry}
            material={materials.blinn1}
            position={[0, 0, 0.05]}
          />
          <mesh
            geometry={nodes.polySurface13_blinn1_0.geometry}
            material={materials.blinn1}
          />
          <mesh
            geometry={nodes.polySurface15_blinn1_0.geometry}
            material={materials.blinn1}
          />
          <mesh
            geometry={nodes.polySurface16_blinn1_0.geometry}
            material={materials.blinn1}
          />
        </group>
        <group position={[0, 0, -0.05]} scale={0.96}>
          <group position={[0, 0, 1.3]} scale={0.75}>
            <mesh
              geometry={nodes.pasted__Cloth_pasted__blinn1_0.geometry}
              material={materials.pasted__blinn1}
            />
            <mesh
              geometry={nodes.pasted__Cloth_pasted__blinn1_0_1.geometry}
              material={materials.pasted__blinn1}
            />
            <mesh
              geometry={nodes.pasted__Cloth_pasted__blinn1_0_2.geometry}
              material={materials.pasted__blinn1}
            />
            <mesh
              geometry={nodes.pasted__Cloth_pasted__blinn1_0_3.geometry}
              material={materials.pasted__blinn1}
            />
          </group>
          <mesh
            geometry={nodes.pasted__KeyCombo_pasted__blinn1_0.geometry}
            material={materials.pasted__blinn1}
            position={[0, 0.04, 0.65]}
            scale={0.69}
          />
          <mesh
            geometry={nodes.pasted__Pads_Material001_0.geometry}
            material={materials["Material.001"]}
            position={[-8.09, -0.19, -5.26]}
            scale={[0.68, 0.36, 0.68]}
          />
          <mesh
            geometry={nodes.pasted__Led_lambert1_0.geometry}
            material={materials.lambert1}
            position={[0, 0.06, 0.04]}
            scale={0.62}
          />
        </group>
        <mesh
          geometry={nodes.polySurface5_blinn2001_0.geometry}
          material={materials["blinn2.001"]}
        />
        <mesh
          geometry={nodes.polySurface7_blinn2001_0.geometry}
          material={materials["blinn2.001"]}
        />
        <mesh
          geometry={nodes.polySurface8001_blinn2001_0.geometry}
          material={materials["blinn2.001"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/tablet-transformed.glb");
